name: dev:prepare

on:
  push:
    branches: [main]
  pull_request:

jobs:
  dev-prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Enable Corepack and activate pnpm from packageManager
        shell: bash
        run: |
          corepack enable
          VER=$(node -p "require('./package.json').packageManager.split('@')[1].split('+')[0]")
          corepack prepare "pnpm@${VER}" --activate
          pnpm -v
      - run: pnpm install
      - run: pnpm rebuild oxc-parser
      - run: pnpm run dev:prepare
