name: Test Suite

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prepare Nuxt (generate .nuxt directory)
        run: pnpm dev:prepare

      - name: Remove .eslintignore if it exists
        run: node -e "try { require('fs').unlinkSync('.eslintignore'); } catch (e) { /* ignore */ }"

      - name: Run unit tests
        run: pnpm test:unit

      - name: Generate coverage report
        run: pnpm test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/lcov.info
          flags: unit
          name: unit-tests

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prepare Nuxt (generate .nuxt directory)
        run: pnpm dev:prepare

      - name: Remove .eslintignore if it exists
        run: node -e "try { require('fs').unlinkSync('.eslintignore'); } catch (e) { /* ignore */ }"

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Build module # Needs prepare step before this
        run: pnpm build

      - name: Run integration tests
        run: pnpm test:integration

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  # accessibility-tests:
  #   name: Accessibility Tests
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #
  #     - name: Install pnpm
  #       uses: pnpm/action-setup@v4
  #
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #         cache: 'pnpm'
  #
  #     - name: Install dependencies
  #       run: pnpm install --frozen-lockfile
  #
  #     - name: Prepare Nuxt (generate .nuxt directory)
  #       run: pnpm dev:prepare
  #
  #     - name: Remove .eslintignore if it exists
  #       run: rm -f .eslintignore
  #
  #     - name: Run accessibility tests
  #       run: pnpm test:accessibility
  #
  #   # TODO: Re-enable when accessibility tests are implemented

  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prepare Nuxt (generate .nuxt directory) # For pnpm build (type check)
        run: pnpm dev:prepare

      - name: Remove .eslintignore if it exists
        run: node -e "try { require('fs').unlinkSync('.eslintignore'); } catch (e) { /* ignore */ }"

      - name: Run linter
        run: pnpm lint

      - name: Check formatting
        run: pnpm format:check

      - name: Type check # This is a pnpm build command
        run: pnpm build

  build-test:
    name: Build Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prepare Nuxt (generate .nuxt directory)
        run: pnpm dev:prepare

      - name: Remove .eslintignore if it exists
        run: node -e "try { require('fs').unlinkSync('.eslintignore'); } catch (e) { /* ignore */ }"

      - name: Build module
        run: pnpm build

      - name: Test playground build
        run: pnpm dev:build

  test-matrix:
    name: Test Matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prepare Nuxt (generate .nuxt directory)
        run: pnpm dev:prepare

      - name: Remove .eslintignore if it exists
        run: node -e "try { require('fs').unlinkSync('.eslintignore'); } catch (e) { /* ignore */ }"

      - name: Run unit tests
        run: pnpm test:unit

      - name: Build module
        run: pnpm build
