name: Simple Test (Validation)

on:
  workflow_dispatch: # Manual trigger for testing
  push: # Also trigger on push for main branch
    branches:
      - main

jobs:
  validate-setup:
    name: Validate PNPM Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Verify pnpm installation
        run: |
          echo "PNPM version:"
          pnpm --version
          echo "Node version:"
          node --version
          echo "NPM version:"
          npm --version

      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json pnpm-lock.yaml
          npm cache clean --force

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Rebuild native modules (oxc-parser, esbuild)
        run: pnpm rebuild oxc-parser esbuild || true

      - name: Prepare Nuxt (generate .nuxt directory)
        run: pnpm dev:prepare

      - name: Remove .eslintignore if it exists
        run: node -e "try { require('fs').unlinkSync('.eslintignore'); } catch (e) { /* ignore */ }"

      - name: Check for .nuxt directory and tsconfig.json
        run: |
          echo "Current directory: $(pwd)"
          echo "Root directory listing:"
          ls -la
          if [ -d ".nuxt" ]; then
            echo ".nuxt directory exists. Listing contents:"
            ls -la .nuxt
            if [ -f ".nuxt/tsconfig.json" ]; then
              echo ".nuxt/tsconfig.json exists."
            else
              echo ".nuxt/tsconfig.json ---- DOES NOT EXIST ----"
            fi
          else
            echo ".nuxt directory ---- DOES NOT EXIST ----"
          fi
          echo "Checking tsconfig.json in playground/.nuxt"
          if [ -d "playground/.nuxt" ]; then
            echo "playground/.nuxt directory exists. Listing contents:"
            ls -la playground/.nuxt
            if [ -f "playground/.nuxt/tsconfig.json" ]; then
              echo "playground/.nuxt/tsconfig.json exists."
            else
              echo "playground/.nuxt/tsconfig.json ---- DOES NOT EXIST ----"
            fi
          else
            echo "playground/.nuxt directory ---- DOES NOT EXIST ----"
          fi

      - name: Verify project setup
        run: |
          echo "Dependencies installed successfully"
          echo "Checking if we can run basic commands:"
          pnpm list --depth=0

      - name: Run unit tests only
        run: pnpm test:unit
